# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(blank=True, max_length=256, null=True)),
                ('followers_count', models.IntegerField(blank=True, null=True)),
                ('friends_count', models.IntegerField(blank=True, null=True)),
                ('statuses_count', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('nit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
