# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('tweet', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('tweet', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'tweets',
                'managed': False,
            },
        ),
    ]
